### ISSUE TITLE
Prove model accuracy as well as merging

### ISSUE THREAD

**Issue by nowittynamesleft** [nowittynamesleft/merkle-tree-models#3]
Need to make a proof of inference on test set, then prove the accuracy on the test set as well, and verify these for each merged model

**Comment by rteehas** [comment]
Added python notebook for acc. proving but proof step hangs

**Comment by nowittynamesleft** [comment]
separated blocks of steps for proof and timed each step in c0b2955 . Step still hangs, but no real CPU usage during the proof step.

**Comment by rteehas** [comment]
Fixed prove step hanging by calibrating with real data (binary tensors instead of real-valued random tensors). Input tensor shape is important. Split data into chunks with fixed batch size before proving & verified each proof
